### ISSUE TITLE
Arming "armed_home" is failing if current Alarmo state is "pending"

### ISSUE THREAD

**Issue by maksimkurb** [array81/alarmo-keypad#1]
Hello. I faced the issue when my Alarmo does not arm successfully.

Scenario:

1. Alarmo in the state "armed_away"
2. Entrance door is opened, door sensor is triggered, Alarmo goes into "pending" state (for exit delay = 2 minutes)
3. (in `pending` state) I press "Arm Home" button on Xfinity XHK1-UE keypad and then enter 4-digit PIN.
4. Xfinity XHK1-UE starts beeping but Alarmo state doesn't changed. I see the following line in the log: `Cannot go to state armed_home from state pending. (custom_components/alarmo/alarm_control_panel.py:393)`

Here in the [Alarmo source code](https://github.com/nielsfaber/alarmo/blob/64368ff62b8e7452f45e0fda414a5652a1403be4/custom_components/alarmo/alarm_control_panel.py#L383-L387) second operand of IF is evaluates as `true`:
`self._state != AlarmControlPanelState.DISARMED and self._state not in const.ARM_MODES`

`self._state` is `pending` and obviously `pending` [is not in ARM_MODES array](https://github.com/nielsfaber/alarmo/blob/64368ff62b8e7452f45e0fda414a5652a1403be4/custom_components/alarmo/const.py#L49-L55).

To fix this issue, blueprint should check current alarmo state and if it's in the `peding` state, it should disarm in the first place and only then it should arm as `armed_home`.

Current workaround: 
1. (after entering house) Disarm by entering 4PIN code
2. Press arm_home button on keypad
3. Enter 4PIN code again to arm home

Entering PIN code twice is not very convenient, but feel free to close this issue if this is indented behaviour.

**Comment by array81** [comment]
I merged your fix, the code works correctly. The only problem is that every time it is activated it sends a notification saying "Already disarmed". We need to delete the notification because it's annoying.

**Comment by maksimkurb** [comment]
Ah, got ya.

Instead of removing notification it's probably better to fix 'if' condition where Alarmo is disarming before arm:
```diff
-             value_template: '{{ "armed_" not in states[alarmo_entity_id].state }}'
+             value_template: '{{ states[alarmo_entity_id].state in ["arming", "pending", "triggered"] }}' 
```

This way Alarmo only disarm (before arming) if it's in "arming", "pending" or"triggered" state.

**Comment by maksimkurb** [comment]
Created a pull request but haven't tried it yet: https://github.com/array81/alarmo-keypad/pull/3

I can test it only on the weekends, currently checked it only on the templates tab
![image](https://github.com/user-attachments/assets/01882a4e-75f2-4df4-bb53-603b009fb1ab)

**Comment by array81** [comment]
Tested. It works.
